---
kind: pipeline
type: docker
name: ubuntu2204

workspace:
  path: /drone/${DRONE_REPO_NAME}

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  # Looking for all .yml files to trigger Lint and Test
  - name: Skip
    image: quay.io/halfwalker/toolset
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qE '.*\/.*.yml|.drone.yml' || exit 78

  - name: Lint
    image: quay.io/halfwalker/toolset
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: quay.io/halfwalker/toolset
    environment:
      MOLECULE_DISTRO: ubuntu2204
      # Set this to name the molecule instance in molecule.yml
      DRONE_REPO_NAME: ${DRONE_REPO_NAME}
      # This defaults to "../.." for local manual running of molecule
      # Drone imports the role into /drone/<rolename> so we have to be explict
      # to find it when drone is running molecule.  See molecule.yml converge.yml
      # ROLE_PATH: /drone/ansible-alacritty
      # https://stackoverflow.com/questions/46366271/using-dind-on-drone-io
      # DOCKER_HOST: "unix:///drone/docker.sock"
      DOCKER_HOST: "tcp://dind:2375"
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - python3 --version
      - ansible --version
      - molecule --version
      - sleep 30
      - docker --version
      - molecule test
    # volumes:
    #   - name: dockersock
    #     path: /var/run

services:
  - name: dind
    image: docker:dind
    privileged: true
    # https://discourse.drone.io/t/port-forwarding-in-drone-services/7803
    # ports:
    #   - port: 2375
    #     host: 12375
    #     protocol: TCP
    # command: [ '-H', 'tcp:///0.0.0.0:2375' ]
    # command: ["--tls=false"]
    commands:
      - dockerd --tls=false --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock -p 0.0.0.0:2375:2375/tcp
    environment:
      DOCKER_TLS_CERTDIR:
    # volumes:
    #   - name: dockersock
    #     path: /var/run

---
kind: pipeline
type: docker
name: ubuntu2004

workspace:
  path: /drone/${DRONE_REPO_NAME}

steps:
  # Skip the pipeline if only changes to README.md or non-drone control files
  - name: Skip
    image: quay.io/halfwalker/toolset
    commands:
      # Grab the incoming commit info to see what changed
      - test $DRONE_BUILD_EVENT = pull_request
          && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-master}
          || DIFF_STRING=${DRONE_COMMIT_SHA}~
      - echo "DIFF_STRING test is $DIFF_STRING"
      # Show the changed files
      - git --no-pager diff --name-only $DIFF_STRING
      # exit 78 to exit cleanly if changes are not in the main files (ignore README etc)
      - git --no-pager diff --name-only $DIFF_STRING | grep -qE '.*\/.*.yml|.drone.yml' || exit 78

  - name: Lint
    image: quay.io/halfwalker/toolset
    commands:
      - yamllint .
      - ansible-lint --force-color

  - name: Molecule
    image: quay.io/halfwalker/toolset
    environment:
      MOLECULE_DISTRO: ubuntu2004
      # Set this to name the molecule instance in molecule.yml
      DRONE_REPO_NAME: ${DRONE_REPO_NAME}
      # This defaults to "../.." for local manual running of molecule
      # Drone imports the role into /drone/<rolename> so we have to be explict
      # to find it when drone is running molecule.  See molecule.yml converge.yml
      # ROLE_PATH: /drone/ansible-alacritty
      # https://stackoverflow.com/questions/46366271/using-dind-on-drone-io
      # DOCKER_HOST: "unix:///drone/docker.sock"
      DOCKER_HOST: "tcp://dind:2375"
      GH_USER:
        from_secret: GH_USER
      GH_TOKEN:
        from_secret: GH_TOKEN
    privileged: true
    commands:
      - python3 --version
      - ansible --version
      - molecule --version
      - sleep 30
      - docker --version
      - molecule test
    # volumes:
    #   - name: dockersock
    #     path: /var/run

services:
  - name: dind
    image: docker:dind
    privileged: true
    # https://discourse.drone.io/t/port-forwarding-in-drone-services/7803
    # ports:
    #   - port: 2375
    #     host: 12375
    #     protocol: TCP
    # command: [ '-H', 'tcp:///0.0.0.0:2375' ]
    # command: ["--tls=false"]
    commands:
      - dockerd --tls=false --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock -p 0.0.0.0:2375:2375/tcp
    environment:
      DOCKER_TLS_CERTDIR:
    # volumes:
    #   - name: dockersock
    #     path: /var/run

# volumes:
#   - name: dockersock
#     temp: {}

