---

#
# This contains all the prep tasks to get ready for gitea as a container
# and then finally runs the container
#

- name: Install support packages
  apt:
    state: present
    install_recommends: no
    update_cache: yes
    name: "{{ gitea_support_packages.common }} + {{ gitea_support_packages[ansible_distribution_release] }}"

# Set home dir to gitea dataset location under git (/stuff/gitea/git)
- name: setup - Create git user for gitea container
  user:
    name: git
    shell: /bin/bash
    home: '{% for dataset in gitea_datasets %}{% if dataset.name == "gitea" %}{{ dataset.mountpoint }}/git{% endif %}{% endfor %}'
    comment: Git user for gitea container
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: git_user

- name: setup - Create extra dirs in ZFS datasets as required
  file:
    path: "{{ item.1 }}"
    state: directory
    owner: "{% if item.0.owner is defined %}{{ item.0.owner }}{% else %}{{ username }}{% endif %}"
    group: "{% if item.0.group is defined %}{{ item.0.group }}{% else %}{{ username }}{% endif %}"
    mode: '0755'
  with_subelements:
    - "{{ gitea_datasets }}"
    - extra_dirs
    - skip_missing: true

# This info is used in the docker .service.j2 files to get UID and GID of main user
- name: setup - Get uid/gid information for docker containers
  getent:
    database: passwd
  check_mode: no

- name: setup - Create git authorized_keys host entry for redirection into docker container
  authorized_key:
    user: git
    state: present
    key: "{{ git_user.ssh_public_key }}"
    key_options: "no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty"

- name: setup - Copy support files (owned by git)
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: git
    group: git
  with_items:
    - { src: gitea_environment, dest: "{{ git_user.home }}/.ssh/environment", mode: "u=rw,g=,o=" }

#
# gitea now uses /usr/local/bin/gitea rather than /app/gitea/gitea
#
- name: setup - Create local man1 dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /usr/local/share/man/man1

- name: setup - Copy support files
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: gitea_local_ssh, dest: '/usr/local/bin/gitea', mode: 'u=rwx,g=rx,o=rx' }
    - { src: avahi-alias@.service, dest: '/etc/systemd/system/avahi-alias@.service', mode: '0644' }

# If runnng under molecule, this may be local testing, in which cast /stuff/gitea may
# already exist. For repeated runs under molecule, we should drop a fresh app.ini into place.
# NOTE: Since app.ini is modified as we go, we do NOT want this task run/tested for idempotence
#       The file will have been modified, so the copy here would be a changed task
# If NOT under molecule, then we definitely do NOT want to overwrite the app.ini, since it
# will have tokens etc. in it that we need to keep.
- name: setup - Copy initial config app.ini
  template:
    src: "{{ item.src }}"
    dest: '{% for dataset in gitea_datasets %}{% if dataset.name == "gitea" %}{{ dataset.mountpoint }}{{ item.dest }}{% endif %}{% endfor %}'
    owner: git
    group: git
    mode: "{{ item.mode }}"
    force: "{{ item.force }}"
  with_items:
    - { src: gitea_app.ini.j2, dest: /gitea/conf/app.ini, mode: '0644', force: "{% if lookup('env', 'MOLECULE_SCENARIO_NAME') %}yes{% else %}no{% endif %}" }
  tags: molecule-idempotence-notest

- name: setup - Copy docker container systemd unit files
  template:
    src:  "{{ item.name }}.service.j2"
    dest: "/etc/systemd/system/{{ item.name }}.service"
    mode: 0644
  with_items:
    - "{{ gitea_containers }}"
  register: gitea_container_systemd
  when: item.name == "gitea"

# - name: setup - Enable avahi-alias publish systemd unit templates
#   systemd:
#     name: "avahi-alias@{{ item.name }}.service"
#     enabled: yes
#   with_items:
#     - "{{ gitea_containers }}"
#   when:
#     - item.publish == true
#     - item.name == "gitea"

# Start just the gitea container so we can do configuration on it
- name: setup - Enable and start gitea
  systemd:
    name: "{{ item.name }}.service"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - "{{ gitea_containers }}"
  register: gitea_start_container
  when: item.name == "gitea"
  ignore_errors: true

# If the systemd unit file changed, then we need to restart the container
- name: setup - Enable and start gitea
  systemd:
    name: "{{ item.name }}.service"
    daemon_reload: yes
    enabled: yes
    state: restarted
  with_items:
    - "{{ gitea_containers }}"
  register: gitea_start_container2
  when:
    - item.name == "gitea"
    - gitea_container_systemd.changed
    - not gitea_start_container.changed
  ignore_errors: true

- name: What containers are running
  command: "docker ps -a"
  become: yes
  register: containers_running
  changed_when: false
  tags: molecule-idempotence-notest

- debug:
    var=containers_running
  tags: molecule-idempotence-notest

- name: Get info on gitea container
  community.general.docker_container_info:
    name: "gitea{% if lookup('env', 'MOLECULE_SCENARIO_NAME') %}-ubuntu-{{ ansible_distribution_release }}{% endif %}"
  register: gitea_container_info

- debug:
    var=gitea_container_info.container.NetworkSettings
    # var=gitea_container_info.container.NetworkSettings.IPAddress

# Since under molecule the container won't necessarily be on the same "host"
# we can't use a plain port check. We have to specify the host the container is
# running on - we get the IP for the container from the tasks just above.  Then
# the host value is just the IP address of the gitea container.
- name: setup - Wait for gitea container to start up
  wait_for:
    host: "{{ gitea_container_info.container.NetworkSettings.IPAddress }}"
    # port: "{% for container in gitea_containers %}{% if container.name == 'gitea' %}{% if container.port is defined %}{{ container.port }}{% else %}3000{% endif %}{% endif %}{% endfor %}"
    port: "{{ gitea_container_port }}"
    delay: 5
  when: gitea_start_container.changed or gitea_start_container.changed2
  tags: molecule-idempotence-notest

